"""initial 13 tables

Revision ID: bd1d9d7a28fa
Revises: 
Create Date: 2026-08-16 13:04:20.087927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd1d9d7a28fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('platform_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_url', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('translated_title', sa.Text(), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_articles_source_external'),
    sa.UniqueConstraint('url', name=op.f('uq_articles_url'))
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('article_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_contents_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_contents'))
    )
    op.create_index(op.f('ix_article_contents_article_id'), 'article_contents', ['article_id'], unique=False)
    op.create_table('article_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_media_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_media'))
    )
    op.create_index(op.f('ix_article_media_article_id'), 'article_media', ['article_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('brief_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_brief_tasks_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brief_tasks'))
    )
    op.create_index(op.f('ix_brief_tasks_user_id'), 'brief_tasks', ['user_id'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_crawl_tasks_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_tasks'))
    )
    op.create_index(op.f('ix_crawl_tasks_user_id'), 'crawl_tasks', ['user_id'], unique=False)
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['brief_tasks.id'], name=op.f('fk_briefs_task_id_brief_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefs'))
    )
    op.create_index(op.f('ix_briefs_task_id'), 'briefs', ['task_id'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('discovered_links', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_crawl_runs_source_id_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['crawl_tasks.id'], name=op.f('fk_crawl_runs_task_id_crawl_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs'))
    )
    op.create_index(op.f('ix_crawl_runs_source_id'), 'crawl_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_task_id'), 'crawl_runs', ['task_id'], unique=False)
    op.create_table('brief_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title_cn', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_brief_items_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], name=op.f('fk_brief_items_brief_id_briefs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brief_items'))
    )
    op.create_index(op.f('ix_brief_items_article_id'), 'brief_items', ['article_id'], unique=False)
    op.create_index(op.f('ix_brief_items_brief_id'), 'brief_items', ['brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brief_items_brief_id'), table_name='brief_items')
    op.drop_index(op.f('ix_brief_items_article_id'), table_name='brief_items')
    op.drop_table('brief_items')
    op.drop_index(op.f('ix_crawl_runs_task_id'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_source_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_briefs_task_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_crawl_tasks_user_id'), table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_brief_tasks_user_id'), table_name='brief_tasks')
    op.drop_table('brief_tasks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_article_media_article_id'), table_name='article_media')
    op.drop_table('article_media')
    op.drop_index(op.f('ix_article_contents_article_id'), table_name='article_contents')
    op.drop_table('article_contents')
    op.drop_table('users')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('system_settings')
    op.drop_table('sources')
    op.drop_table('roles')
    # ### end Alembic commands ###